services:
    bot:
        build: .
        container_name: expense-bot
        restart: unless-stopped
        env_file: .env
        depends_on:
            - mongo
        networks:
            - app-network
        dns:
            - 8.8.8.8
            - 1.1.1.1

    mongo:
        image: mongo:6
        container_name: mongo-db
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
        networks:
            - app-network

volumes:
    mongo-data:

networks:
    app-network:
